window.EXTRA_LANDMARKS = {
  "Algeria": { name: "Casbah of Algiers", fact: "A hillside city of white houses and winding lanes above the sea." },
  "Angola": { name: "Fortress of São Miguel", fact: "An old stone fort that looks out over Luanda's bay." },
  "Benin": { name: "Royal Palaces of Abomey", fact: "A line of royal courts built by the kings of Dahomey." },
  "Botswana": { name: "Okavango Delta", fact: "A river that spreads into a maze of islands instead of reaching the sea." },
  "Burkina Faso": { name: "Grand Mosque of Bobo-Dioulasso", fact: "A mud-brick mosque with wooden beams sticking out of the walls." },
  "Burundi": { name: "Lake Tanganyika", fact: "One of the deepest lakes on Earth, on Burundi's western edge." },
  "Cameroon": { name: "Mount Cameroon", fact: "A huge volcano that rises straight out of the Atlantic coast." },
  "Cape Verde": { name: "Cidade Velha", fact: "A tiny harbour town that was one of the first European ports in the tropics." },
  "Central African Republic": { name: "Boali Falls", fact: "A wide waterfall on the Mbali River, a short drive from Bangui." },
  "Chad": { name: "Lakes of Ounianga", fact: "A chain of desert lakes that stay blue even in the Sahara." },
  "Comoros": { name: "Mount Karthala", fact: "An active volcano that makes up most of the largest island." },
  "Congo (DRC)": { name: "Virunga National Park", fact: "Home to mountain gorillas and a chain of volcanoes." },
  "Congo (Republic)": { name: "Congo River rapids", fact: "The river turns wild with rapids just beside Brazzaville." },
  "Côte d'Ivoire": { name: "Basilica of Our Lady of Peace", fact: "A giant church in Yamoussoukro, bigger than it first looks." },
  "Djibouti": { name: "Lake Assal", fact: "A salt lake that sits below sea level and shines white in the sun." },
  "Equatorial Guinea": { name: "Pico Basile", fact: "A volcano that rises over the capital, Malabo, on Bioko island." },
  "Eritrea": { name: "Asmara's old cinemas", fact: "The capital is full of 1930s buildings that look like film sets." },
  "Eswatini": { name: "Mantenga Falls", fact: "A waterfall that drops into a green gorge near the capital." },
  "Ethiopia": { name: "Churches of Lalibela", fact: "Churches carved down into solid rock, still used today." },
  "Gabon": { name: "Loango coast", fact: "A wild beach where forest, elephants, and the Atlantic meet." },
  "Gambia": { name: "Kunta Kinteh Island", fact: "A small island in the river with a long, serious history." },
  "Ghana": { name: "Cape Coast Castle", fact: "A white fort on the waves, important in the story of the Atlantic trade." },
  "Guinea": { name: "Mount Nimba", fact: "A sharp mountain on the border, wrapped in cloud forest." },
  "Guinea-Bissau": { name: "Bijagós Islands", fact: "A scatter of islands where tides cover the paths twice a day." },
  "Kenya": { name: "Maasai Mara", fact: "Open grassland where huge herds pass through every year." },
  "Lesotho": { name: "Maletsunyane Falls", fact: "A single ribbon of water falling into a deep gorge." },
  "Liberia": { name: "Providence Island", fact: "The small island in Monrovia where the city began." },
  "Libya": { name: "Leptis Magna", fact: "A Roman city of columns standing in the sand by the sea." },
  "Madagascar": { name: "Avenue of the Baobabs", fact: "A dirt road lined with enormous bottle-shaped trees." },
  "Malawi": { name: "Lake Malawi", fact: "A long, clear lake that looks like an inland sea." },
  "Mali": { name: "Great Mosque of Djenné", fact: "The world's largest mud-brick building, smoothed by hand each year." },
  "Mauritania": { name: "Chinguetti", fact: "A sandstone town at the edge of the Sahara, famous for old libraries." },
  "Mauritius": { name: "Le Morne Brabant", fact: "A steep rock rising out of the lagoon at the island's tip." },
  "Morocco": { name: "Jemaa el-Fnaa", fact: "Marrakech's big square, full of food stalls, music, and storytellers." },
  "Mozambique": { name: "Island of Mozambique", fact: "A tiny coral island with a stone town and a star-shaped fort." },
  "Namibia": { name: "Sossusvlei", fact: "Orange sand dunes so tall they make people look like ants." },
  "Niger": { name: "Mosque of Agadez", fact: "A mud minaret that has watched the desert town for centuries." },
  "Nigeria": { name: "Zuma Rock", fact: "A huge dark rock face that stands alone beside the road to Abuja." },
  "Rwanda": { name: "Volcanoes National Park", fact: "Misty mountains where gorillas live in the bamboo." },
  "São Tomé and Príncipe": { name: "Pico Cão Grande", fact: "A needle of volcanic rock sticking out of the jungle." },
  "Senegal": { name: "Gorée Island", fact: "A small island just off Dakar, quiet and important." },
  "Seychelles": { name: "Anse Source d'Argent", fact: "A beach of pink-white sand and giant granite boulders." },
  "Sierra Leone": { name: "Tacugama", fact: "A forest sanctuary in the hills above Freetown, known for chimpanzees." },
  "Somalia": { name: "Laas Geel", fact: "Rock shelters painted with cattle thousands of years ago." },
  "South Africa": { name: "Table Mountain", fact: "A flat-topped mountain that makes a roof over Cape Town." },
  "South Sudan": { name: "The White Nile at Juba", fact: "The great river that the capital sits beside." },
  "Sudan": { name: "Pyramids of Meroë", fact: "Sharp little pyramids standing in the desert, older than you might think." },
  "Togo": { name: "Koutammakou", fact: "Villages of tall clay tower-houses built by the Batammariba people." },
  "Tunisia": { name: "Amphitheatre of El Jem", fact: "A Roman arena so big it rivals the ones in Italy." },
  "Uganda": { name: "Murchison Falls", fact: "The Nile squeezed through a gap in the rock, then exploding out." },
  "Zambia": { name: "Victoria Falls", fact: "A waterfall so wide the spray can be seen from far away." },
  "Zimbabwe": { name: "Great Zimbabwe", fact: "Stone walls of an old city, built without mortar." },
  "Afghanistan": { name: "Buddhas of the Bamiyan valley", fact: "The cliff niches remain, looking over a high green valley." },
  "Armenia": { name: "Geghard Monastery", fact: "A church partly cut into the cliff, up a rocky gorge." },
  "Azerbaijan": { name: "Maiden Tower", fact: "A mystery tower in Baku's old walled city by the Caspian." },
  "Bahrain": { name: "Bahrain Fort", fact: "Layers of forts and cities stacked on a mound by the sea." },
  "Bangladesh": { name: "Sundarbans", fact: "The world's biggest mangrove forest, home of the Bengal tiger." },
  "Bhutan": { name: "Tiger's Nest", fact: "A monastery stuck to a cliff high above the valley." },
  "Brunei": { name: "Omar Ali Saifuddien Mosque", fact: "A golden dome reflected in a lagoon in the capital." },
  "Georgia": { name: "Gergeti Trinity Church", fact: "A small church on a hill, with Kazbek mountain behind it." },
  "Indonesia": { name: "Borobudur", fact: "A giant stone temple covered in bell-shaped stupas." },
  "Iran": { name: "Persepolis", fact: "The ruined palace city of ancient Persia, with carved stairways." },
  "Iraq": { name: "The ziggurat of Ur", fact: "A stepped mud-brick temple from one of the world's oldest cities." },
  "Israel": { name: "The Old City of Jerusalem", fact: "Stone lanes, markets, and holy places inside high walls." },
  "Kazakhstan": { name: "Khan Shatyr", fact: "A tent-shaped glass building rising over Astana." },
  "Kuwait": { name: "Kuwait Towers", fact: "Blue-and-white spheres on stalks, looking over the Gulf." },
  "Kyrgyzstan": { name: "Lake Issyk-Kul", fact: "A huge mountain lake that does not freeze in winter." },
  "Laos": { name: "Luang Prabang", fact: "A riverside town of temples and morning alms." },
  "Lebanon": { name: "Baalbek", fact: "Roman temples with columns taller than most trees." },
  "Malaysia": { name: "Petronas Towers", fact: "Twin skyscrapers linked by a bridge in the sky." },
  "Maldives": { name: "The coral atolls", fact: "Rings of tiny islands sitting on reefs in a blue sea." },
  "Mongolia": { name: "Genghis Khan statue complex", fact: "A giant rider looking over the steppe east of the capital." },
  "Myanmar": { name: "Bagan", fact: "Thousands of temples scattered across a dusty plain." },
  "Nepal": { name: "Mount Everest", fact: "The highest mountain on Earth, on Nepal's border with China." },
  "North Korea": { name: "Tower of the Juche Idea", fact: "A tall stone torch-tower on the river in Pyongyang." },
  "Oman": { name: "Sultan Qaboos Grand Mosque", fact: "A vast white mosque with a single huge chandelier." },
  "Pakistan": { name: "Badshahi Mosque", fact: "A red-sandstone mosque facing the fort in Lahore." },
  "Palestine": { name: "Church of the Nativity", fact: "A church in Bethlehem built over a very old cave." },
  "Philippines": { name: "Chocolate Hills", fact: "Hundreds of round green hills that turn brown in the dry season." },
  "Qatar": { name: "Museum of Islamic Art", fact: "A pale stone building on its own island in Doha's bay." },
  "Saudi Arabia": { name: "AlUla", fact: "Sandstone canyons and old tombs carved into the cliffs." },
  "Singapore": { name: "Gardens by the Bay", fact: "Supertrees and glass domes on the waterfront." },
  "South Korea": { name: "Gyeongbokgung", fact: "A grand palace of wooden halls in the middle of Seoul." },
  "Sri Lanka": { name: "Sigiriya", fact: "A palace fortress on top of a sheer rock." },
  "Syria": { name: "The old city of Damascus", fact: "One of the oldest cities still lived in, with a covered market." },
  "Tajikistan": { name: "Iskanderkul", fact: "A turquoise lake in the mountains, named for Alexander." },
  "Thailand": { name: "The Grand Palace", fact: "Gold spires and a famous emerald Buddha in Bangkok." },
  "Timor-Leste": { name: "Cristo Rei", fact: "A statue on a hill above the sea at Dili." },
  "Turkey": { name: "Cappadocia", fact: "Fairy chimneys of soft rock, with caves people still use." },
  "Turkmenistan": { name: "Darvaza gas crater", fact: "A pit in the desert that has been burning for decades." },
  "Uzbekistan": { name: "Registan", fact: "Three tiled madrasas facing a square in Samarkand." },
  "Vietnam": { name: "Ha Long Bay", fact: "Limestone islands rising out of green water." },
  "Yemen": { name: "Old Sana'a", fact: "Tall brown tower-houses decorated with white plaster patterns." },
  "Antigua and Barbuda": { name: "Nelson's Dockyard", fact: "A restored harbour where sailing ships still tie up." },
  "Bahamas": { name: "The blue holes", fact: "Deep round pools of blue water in the limestone." },
  "Barbados": { name: "Harrison's Cave", fact: "A cave of underground streams and pale stalactites." },
  "Cuba": { name: "Old Havana", fact: "Pastel streets, old cars, and a sea wall called the Malecón." },
  "Dominica": { name: "Boiling Lake", fact: "A lake that really steams, hidden in the mountain forest." },
  "Dominican Republic": { name: "The Colonial Zone", fact: "The old walled centre of Santo Domingo, the first European city in the Americas." },
  "Grenada": { name: "Grand Anse Beach", fact: "A long curve of sand with green hills behind it." },
  "Haiti": { name: "Citadelle Laferrière", fact: "A huge hilltop fort built of stone after independence." },
  "Jamaica": { name: "Dunn's River Falls", fact: "A staircase of water you can climb beside the beach." },
  "Saint Kitts and Nevis": { name: "Brimstone Hill Fortress", fact: "A stone fort on a hill, looking over the Caribbean." },
  "Saint Lucia": { name: "The Pitons", fact: "Two volcanic peaks that jump straight out of the sea." },
  "Saint Vincent and the Grenadines": { name: "La Soufrière", fact: "A volcano that watches over the island's north end." },
  "Trinidad and Tobago": { name: "Caroni Swamp", fact: "Mangroves where scarlet ibises come in to roost at dusk." },
  "Belize": { name: "Great Blue Hole", fact: "A perfect dark-blue circle in the reef, seen best from above." },
  "Costa Rica": { name: "Arenal Volcano", fact: "A cone-shaped volcano above hot springs and rainforest." },
  "El Salvador": { name: "Joya de Cerén", fact: "A village buried by a volcano, sometimes called the Pompeii of the Americas." },
  "Guatemala": { name: "Tikal", fact: "Maya pyramids rising out of the jungle." },
  "Honduras": { name: "Copán", fact: "Maya ruins famous for their carved stone stairway." },
  "Nicaragua": { name: "Granada's colourful streets", fact: "A lakeside city of painted houses and horse-drawn carriages." },
  "Panama": { name: "Panama Canal", fact: "Ships climb through locks from one ocean to the other." },
  "Albania": { name: "Berat", fact: "A town of white houses stacked up a hill, called the city of a thousand windows." },
  "Andorra": { name: "Grandvalira", fact: "High ski slopes in the Pyrenees above the little capital." },
  "Austria": { name: "Schönbrunn Palace", fact: "A yellow palace with a huge garden and a hilltop view of Vienna." },
  "Belarus": { name: "Mir Castle", fact: "A red-and-white castle reflected in a still lake." },
  "Belgium": { name: "Grand-Place", fact: "A square in Brussels lined with gold-trimmed guild houses." },
  "Bosnia and Herzegovina": { name: "Stari Most", fact: "A high stone bridge leaping over the river in Mostar." },
  "Bulgaria": { name: "Rila Monastery", fact: "A painted monastery tucked into a pine forest." },
  "Croatia": { name: "Dubrovnik walls", fact: "Stone walls around a marble old town on the Adriatic." },
  "Cyprus": { name: "Petra tou Romiou", fact: "The sea stack where legend says Aphrodite came ashore." },
  "Czech Republic": { name: "Charles Bridge", fact: "A statue-lined bridge across the river in Prague." },
  "Denmark": { name: "Nyhavn", fact: "A harbour of bright skinny houses and wooden ships." },
  "Estonia": { name: "Tallinn old town", fact: "A walled medieval city with red roofs and church spires." },
  "Finland": { name: "Suomenlinna", fact: "A sea fortress spread over islands outside Helsinki." },
  "Hungary": { name: "Parliament Building", fact: "A huge riverside palace of spires in Budapest." },
  "Iceland": { name: "Gullfoss", fact: "A two-step waterfall in a canyon of black rock." },
  "Ireland": { name: "Cliffs of Moher", fact: "Sea cliffs that drop straight into the Atlantic." },
  "Latvia": { name: "Riga old town", fact: "Art Nouveau streets and a square of colourful merchant houses." },
  "Liechtenstein": { name: "Vaduz Castle", fact: "A castle on a crag right above the tiny capital." },
  "Lithuania": { name: "Hill of Crosses", fact: "A hill covered in thousands of crosses left by visitors." },
  "Luxembourg": { name: "The Bock casemates", fact: "Tunnels and bridges cut through the rock under the old city." },
  "Malta": { name: "Valletta harbours", fact: "A fortified city between two deep blue harbours." },
  "Moldova": { name: "Cricova wine cellars", fact: "A whole underground town of wine tunnels." },
  "Monaco": { name: "The Prince's Palace", fact: "A palace on the rock, looking down on the harbour of yachts." },
  "Montenegro": { name: "Bay of Kotor", fact: "A fjord-like bay with a walled town at the water's edge." },
  "Netherlands": { name: "Kinderdijk", fact: "A row of windmills standing over flat green fields." },
  "North Macedonia": { name: "Lake Ohrid", fact: "An ancient lake with a town of churches on its shore." },
  "Norway": { name: "Geirangerfjord", fact: "A deep blue fjord with waterfalls dropping off the cliffs." },
  "Poland": { name: "Wawel Castle", fact: "A castle on a hill above the river in Kraków." },
  "Portugal": { name: "Belém Tower", fact: "A stone tower that once guarded the mouth of Lisbon's river." },
  "Romania": { name: "Bran Castle", fact: "A hill castle often linked with the Dracula stories." },
  "San Marino": { name: "The Three Towers", fact: "Stone towers on the ridges of a tiny mountain republic." },
  "Serbia": { name: "Belgrade Fortress", fact: "A fort where two great rivers meet, above the capital." },
  "Slovakia": { name: "Spiš Castle", fact: "One of the biggest castle ruins in Europe, on a pale hill." },
  "Slovenia": { name: "Lake Bled", fact: "A church on an island in a lake, with a castle on the cliff." },
  "Sweden": { name: "Vasa Museum", fact: "A wooden warship that sank in 1628 and was pulled up almost whole." },
  "Switzerland": { name: "Matterhorn", fact: "A pyramid of rock and snow above the village of Zermatt." },
  "Ukraine": { name: "Saint Sophia's Cathedral", fact: "A golden-domed cathedral in the heart of Kyiv." },
  "Vatican City": { name: "St. Peter's Basilica", fact: "The great church at the centre of the tiny country." },
  "Canada": { name: "Niagara Falls", fact: "A thunder of water on the border, lit up at night." },
  "Fiji": { name: "The Mamanuca Islands", fact: "A string of small islands in clear water off the main island." },
  "Kiribati": { name: "Tarawa atoll", fact: "A thin ribbon of land around a huge lagoon." },
  "Marshall Islands": { name: "Bikini Atoll lagoon", fact: "A wide, quiet lagoon with a famous place in history." },
  "Micronesia": { name: "Nan Madol", fact: "A city of basalt logs built on canals off Pohnpei." },
  "Nauru": { name: "Command Ridge", fact: "The island's highest point, with a view of the whole coast." },
  "New Zealand": { name: "Milford Sound", fact: "A fjord of dark water and waterfalls under steep peaks." },
  "Palau": { name: "Rock Islands", fact: "Mushroom-shaped limestone islands in pale green water." },
  "Papua New Guinea": { name: "Kokoda Track", fact: "A jungle path over the mountains, famous from the war." },
  "Samoa": { name: "To Sua ocean trench", fact: "A swimming hole in a collapsed cave, with a ladder down to the sea." },
  "Solomon Islands": { name: "Marovo Lagoon", fact: "A huge lagoon of reefs and forested islands." },
  "Tonga": { name: "Mapu'a 'a Vaea", fact: "Blowholes where the ocean shoots up through the rock." },
  "Tuvalu": { name: "Funafuti lagoon", fact: "The main island is a thin ring around a bright lagoon." },
  "Vanuatu": { name: "Mount Yasur", fact: "A volcano you can walk up to and watch the lava burst." },
  "Argentina": { name: "Iguazú Falls", fact: "A horseshoe of waterfalls on the border with Brazil." },
  "Bolivia": { name: "Salar de Uyuni", fact: "A salt flat so big and flat it mirrors the sky." },
  "Chile": { name: "Moai of Easter Island", fact: "Giant stone figures standing on a lonely Pacific island." },
  "Colombia": { name: "Cartagena's walls", fact: "A colourful old city inside thick stone ramparts." },
  "Ecuador": { name: "The Galápagos Islands", fact: "Volcanic islands where giant tortoises still walk the trails." },
  "Guyana": { name: "Kaieteur Falls", fact: "A single enormous drop in the rainforest." },
  "Paraguay": { name: "Jesuit ruins of Trinidad", fact: "Red-stone mission ruins standing in the grass." },
  "Suriname": { name: "Paramaribo's wooden city", fact: "A capital of painted wooden houses along the river." },
  "Uruguay": { name: "Rambla of Montevideo", fact: "A long seaside promenade where the city meets the river." },
  "Venezuela": { name: "Angel Falls", fact: "The world's tallest waterfall, dropping off a tabletop mountain." },
};
